### ISSUE TITLE
StyleGAN3-NADA pretrained models

### ISSUE THREAD

**Issue by garchilingaryan** [yuval-alaluf/stylegan3-editing#9]
Hi there! Thanks for your awesome work!

I was browsing through the StyleGAN3-NADA branch with hope to find some pretrained StyleGAN3 models for different style effects, but the only ones that I found are for StyleGAN2. I was wondering if you could provide some of the pretrained  StyleGAN3-NADA models that you used for your project or maybe give a hint of where I can find them?

Thanks in advance!

**Comment by woctezuma** [comment]
What is StyleGAN3-NADA? I only know about StyleGAN2-ADA.

**Comment by yuval-alaluf** [comment]
I can try collecting some models and upload them to the repository. But our results with StyleGAN-NADA were obtained without modifying the original code that can be found here: https://github.com/rinongal/StyleGAN-nada/tree/StyleGAN3-NADA

Since training is quick, you could try training some of your own models in the meantime. 

The code should work out-of-the-box.

**Comment by garchilingaryan** [comment]
Thank you so much! Will be looking forward to your models. I will try to train some models by myself as well the way you suggested!

**Comment by yuval-alaluf** [comment]
I just finished uploading a handful of models for multiple generators. Take a look here: 
https://github.com/yuval-alaluf/stylegan3-editing#stylegan-nada

Enjoy :)
